language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - softwaredev-notify@wwwh.com
    on_success: never
    on_failure: always
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - jruby-19mode
